# haproxy.cfg 파일을 통해 web 3개 기동 가능.
# docker compose up -d --scale web=3   ==========> web-1, web-2. web-3 생성
#
# docker run -d --name web1 --net mynetwork jmalloc/echo-server
services:
  web:
    image: jmalloc/echo-server

# # docker run -d --name haproxy --net mynetwork \
#-v $(pwd):/usr/local/etc/haproxy:ro \
#-p 80:80 -p 8404:8404 haproxytech/haproxy-alpine:2.7
  haproxy:
    image: haproxytech/haproxy-alpine:2.7
    volumes:
      - "./config:/usr/local/etc/haproxy:ro"
    ports:
      - "80:80"
    depends_on:
      - web
